// Catálogo de categorias/serviços de publicidade que um inquilino (agência/emissora)
// pode oferecer. Usado no cadastro do inquilino no Painel do Proprietário.

export type CategoriaServico = {
  key: string;
  label: string;
  itens: { key: string; label: string; subitens?: { key: string; label: string }[] }[];
};

export const CATEGORIAS_SERVICOS: CategoriaServico[] = [
  {
    key: "planejamento",
    label: "1. Planejamento Estratégico",
    itens: [
      { key: "plano_comunicacao", label: "Plano de Comunicação" },
      { key: "plano_midia", label: "Plano de Mídia" },
      { key: "planejamento_campanhas", label: "Planejamento de Campanhas" },
      { key: "posicionamento_marca", label: "Posicionamento de Marca" },
      { key: "estrategia_comercial", label: "Estratégia Comercial" },
      { key: "estrategia_lancamentos", label: "Estratégia de Lançamentos" },
      { key: "plan_anual_mkt", label: "Planejamento Anual de Marketing" },
      { key: "analise_concorrencia", label: "Análise de Concorrência" },
      { key: "pesquisa_mercado", label: "Pesquisa de Mercado" },
      { key: "diagnostico_marca", label: "Diagnóstico de Marca" },
      { key: "definicao_publico", label: "Definição de Público-Alvo" },
      { key: "jornada_cliente", label: "Jornada do Cliente" },
      { key: "funil_vendas", label: "Funil de Vendas" },
      { key: "estrategia_omnichannel", label: "Estratégia Omnichannel" },
      { key: "planejamento_eventos", label: "Planejamento de Eventos" },
    ],
  },
  {
    key: "midia",
    label: "2. Compra e Negociação de Mídia",
    itens: [
      {
        key: "tv",
        label: "TV",
        subitens: [
          { key: "tv_aberta", label: "TV Aberta" },
          { key: "tv_assinatura", label: "TV por Assinatura" },
          { key: "tv_merchandising", label: "Merchandising" },
          { key: "tv_programas_especiais", label: "Programas Especiais" },
          { key: "tv_patrocinio", label: "Patrocínio" },
          { key: "tv_vinhetas", label: "Vinhetas" },
        ],
      },
      {
        key: "radio",
        label: "Rádio",
        subitens: [
          { key: "radio_spots", label: "Spots" },
          { key: "radio_testemunhal", label: "Testemunhal" },
          { key: "radio_patrocinio", label: "Patrocínio" },
          { key: "radio_programas_especiais", label: "Programas Especiais" },
          { key: "radio_flash", label: "Flash ao Vivo" },
        ],
      },
      {
        key: "jornal",
        label: "Jornal",
        subitens: [
          { key: "jornal_pg_inteira", label: "Página inteira" },
          { key: "jornal_meia", label: "Meia página" },
          { key: "jornal_encartes", label: "Encartes" },
          { key: "jornal_classificados", label: "Classificados" },
        ],
      },
      {
        key: "revista",
        label: "Revista",
        subitens: [
          { key: "revista_anuncios", label: "Anúncios" },
          { key: "revista_publieditorial", label: "Publieditorial" },
        ],
      },
      {
        key: "outdoor",
        label: "Outdoor",
        subitens: [
          { key: "outdoor_tradicional", label: "Outdoor tradicional" },
          { key: "outdoor_frontlight", label: "Front Light" },
          { key: "outdoor_backlight", label: "Back Light" },
          { key: "outdoor_empena", label: "Empena" },
          { key: "outdoor_rodoviario", label: "Painel Rodoviário" },
          { key: "outdoor_busdoor", label: "Busdoor" },
          { key: "outdoor_taxidoor", label: "Taxidoor" },
        ],
      },
      {
        key: "dooh",
        label: "DOOH (Mídia Digital Out of Home)",
        subitens: [
          { key: "dooh_led", label: "Painéis LED" },
          { key: "dooh_relogios", label: "Relógios digitais" },
          { key: "dooh_totens", label: "Totens" },
          { key: "dooh_elevadores", label: "Elevadores" },
          { key: "dooh_shopping", label: "Shopping Centers" },
          { key: "dooh_aeroportos", label: "Aeroportos" },
          { key: "dooh_rodoviarias", label: "Rodoviárias" },
        ],
      },
    ],
  },
  {
    key: "digital",
    label: "3. Marketing Digital",
    itens: [
      { key: "gestao_instagram", label: "Gestão de Instagram" },
      { key: "gestao_facebook", label: "Gestão de Facebook" },
      { key: "gestao_linkedin", label: "LinkedIn" },
      { key: "gestao_tiktok", label: "TikTok" },
      { key: "gestao_pinterest", label: "Pinterest" },
      { key: "gestao_youtube", label: "YouTube" },
      { key: "calendario_editorial", label: "Calendário Editorial" },
      { key: "producao_conteudo", label: "Produção de Conteúdo" },
      { key: "copywriting", label: "Copywriting" },
      { key: "reels", label: "Reels" },
      { key: "stories", label: "Stories" },
      { key: "carrosseis", label: "Carrosséis" },
      { key: "gestao_comunidade", label: "Gestão de Comunidade" },
      { key: "sac_digital", label: "SAC Digital" },
    ],
  },
  {
    key: "trafego_pago",
    label: "4. Tráfego Pago",
    itens: [
      { key: "google_ads", label: "Google Ads" },
      { key: "meta_ads", label: "Meta Ads" },
      { key: "linkedin_ads", label: "LinkedIn Ads" },
      { key: "tiktok_ads", label: "TikTok Ads" },
      { key: "youtube_ads", label: "YouTube Ads" },
      { key: "waze_ads", label: "Waze Ads" },
      { key: "ads_pesquisa", label: "Pesquisa" },
      { key: "ads_display", label: "Display" },
      { key: "ads_video", label: "Vídeo" },
      { key: "ads_remarketing", label: "Remarketing" },
      { key: "ads_pmax", label: "Performance Max" },
      { key: "ads_leads", label: "Geração de Leads" },
    ],
  },
  {
    key: "branding",
    label: "5. Branding",
    itens: [
      { key: "criacao_marca", label: "Criação de Marca" },
      { key: "rebranding", label: "Rebranding" },
      { key: "manual_marca", label: "Manual da Marca" },
      { key: "identidade_visual", label: "Identidade Visual" },
      { key: "naming", label: "Naming" },
      { key: "posicionamento", label: "Posicionamento" },
      { key: "arquitetura_marca", label: "Arquitetura de Marca" },
    ],
  },
  {
    key: "design",
    label: "6. Design",
    itens: [
      { key: "logotipo", label: "Logotipo" },
      { key: "papelaria", label: "Papelaria" },
      { key: "cartao", label: "Cartão" },
      { key: "folder", label: "Folder" },
      { key: "catalogo", label: "Catálogo" },
      { key: "apresentacoes", label: "Apresentações" },
      { key: "propostas_comerciais", label: "Propostas Comerciais" },
      { key: "banners", label: "Banners" },
      { key: "design_outdoor", label: "Outdoor" },
      { key: "design_paineis", label: "Painéis" },
      { key: "cardapios", label: "Cardápios" },
      { key: "embalagens", label: "Embalagens" },
    ],
  },
  {
    key: "audiovisual",
    label: "7. Produção Audiovisual",
    itens: [
      { key: "comercial_tv", label: "Comercial para TV" },
      { key: "video_institucional", label: "Vídeo Institucional" },
      { key: "av_reels", label: "Reels" },
      { key: "av_stories", label: "Stories" },
      { key: "captacao", label: "Captação" },
      { key: "drone", label: "Drone" },
      { key: "fotografia", label: "Fotografia" },
      { key: "edicao", label: "Edição" },
      { key: "motion_graphics", label: "Motion Graphics" },
      { key: "av_vinhetas", label: "Vinhetas" },
    ],
  },
  {
    key: "eventos",
    label: "8. Eventos",
    itens: [
      { key: "lancamentos", label: "Lançamentos" },
      { key: "feiras", label: "Feiras" },
      { key: "congressos", label: "Congressos" },
      { key: "corridas", label: "Corridas" },
      { key: "shows", label: "Shows" },
      { key: "exposicoes", label: "Exposições" },
      { key: "convencoes", label: "Convenções" },
      { key: "coletivas", label: "Coletivas" },
      { key: "patrocinios", label: "Patrocínios" },
      { key: "ativacoes", label: "Ativações" },
      { key: "cenografia", label: "Cenografia" },
      { key: "credenciamento", label: "Credenciamento" },
      { key: "producao", label: "Produção" },
      { key: "cobertura", label: "Cobertura" },
    ],
  },
  {
    key: "patrocinios",
    label: "9. Patrocínios",
    itens: [
      { key: "patr_corridas", label: "Corridas" },
      { key: "patr_rodeios", label: "Rodeios" },
      { key: "patr_festivais", label: "Festivais" },
      { key: "patr_corporativos", label: "Eventos Corporativos" },
      { key: "patr_esportivos", label: "Eventos Esportivos" },
      { key: "patr_feiras", label: "Feiras" },
      { key: "patr_congressos", label: "Congressos" },
      { key: "patr_comercializacao_cotas", label: "Comercialização de cotas" },
      { key: "patr_captacao", label: "Captação de patrocinadores" },
      { key: "patr_relatorios", label: "Relatórios" },
      { key: "patr_entregas", label: "Entregas" },
    ],
  },
  {
    key: "representacao",
    label: "10. Representação Comercial",
    itens: [
      { key: "rep_tvs", label: "TVs" },
      { key: "rep_radios", label: "Rádios" },
      { key: "rep_portais", label: "Portais" },
      { key: "rep_influenciadores", label: "Influenciadores" },
      { key: "rep_led", label: "Painéis de LED" },
      { key: "rep_outdoor", label: "Outdoor" },
      { key: "rep_revistas", label: "Revistas" },
      { key: "rep_eventos", label: "Eventos" },
      { key: "rep_feiras", label: "Feiras" },
      { key: "rep_podcasts", label: "Podcasts" },
    ],
  },
  {
    key: "influencia",
    label: "11. Marketing de Influência",
    itens: [
      { key: "inf_selecao", label: "Seleção de Influenciadores" },
      { key: "inf_negociacao", label: "Negociação" },
      { key: "inf_contratos", label: "Contratos" },
      { key: "inf_campanhas", label: "Campanhas" },
      { key: "inf_gestao", label: "Gestão" },
      { key: "inf_relatorios", label: "Relatórios" },
    ],
  },
  {
    key: "assessoria",
    label: "12. Assessoria Comercial",
    itens: [
      { key: "estrutur_comercial", label: "Estruturação Comercial" },
      { key: "crm", label: "CRM" },
      { key: "funil", label: "Funil" },
      { key: "treinamentos", label: "Treinamentos" },
      { key: "scripts", label: "Scripts" },
      { key: "gestao_carteira", label: "Gestão de Carteira" },
      { key: "prospeccao", label: "Prospecção" },
    ],
  },
  {
    key: "consultoria",
    label: "13. Consultoria",
    itens: [
      { key: "cons_marketing", label: "Marketing" },
      { key: "cons_comunicacao", label: "Comunicação" },
      { key: "cons_branding", label: "Branding" },
      { key: "cons_comercial", label: "Comercial" },
      { key: "cons_posicionamento", label: "Posicionamento" },
      { key: "cons_inteligencia", label: "Inteligência de Mercado" },
    ],
  },
  {
    key: "dados",
    label: "14. Inteligência de Dados",
    itens: [
      { key: "dashboards", label: "Dashboards" },
      { key: "bi", label: "BI" },
      { key: "kpis", label: "KPIs" },
      { key: "dados_relatorios", label: "Relatórios" },
      { key: "roi", label: "ROI" },
      { key: "cac", label: "CAC" },
      { key: "ltv", label: "LTV" },
      { key: "performance", label: "Performance" },
    ],
  },
  {
    key: "dev_digital",
    label: "15. Desenvolvimento Digital",
    itens: [
      { key: "sites", label: "Sites" },
      { key: "landing_pages", label: "Landing Pages" },
      { key: "ecommerce", label: "E-commerce" },
      { key: "blogs", label: "Blogs" },
      { key: "portais", label: "Portais" },
      { key: "seo", label: "SEO" },
      { key: "hospedagem", label: "Hospedagem" },
    ],
  },
  {
    key: "impressos",
    label: "16. Impressos",
    itens: [
      { key: "panfletos", label: "Panfletos" },
      { key: "imp_folders", label: "Folders" },
      { key: "imp_catalogos", label: "Catálogos" },
      { key: "imp_revistas", label: "Revistas" },
      { key: "cartazes", label: "Cartazes" },
      { key: "imp_banners", label: "Banners" },
      { key: "faixas", label: "Faixas" },
      { key: "adesivos", label: "Adesivos" },
      { key: "imp_totens", label: "Totens" },
      { key: "fachadas", label: "Fachadas" },
    ],
  },
  {
    key: "corporativa",
    label: "17. Comunicação Corporativa",
    itens: [
      { key: "com_interna", label: "Comunicação Interna" },
      { key: "endomarketing_corp", label: "Endomarketing" },
      { key: "newsletters", label: "Newsletters" },
      { key: "corp_apresentacoes", label: "Apresentações" },
      { key: "corp_relatorios", label: "Relatórios" },
      { key: "materiais_institucionais", label: "Materiais Institucionais" },
    ],
  },
  {
    key: "endomarketing",
    label: "18. Endomarketing",
    itens: [
      { key: "campanhas_internas", label: "Campanhas Internas" },
      { key: "datas_comemorativas", label: "Datas Comemorativas" },
      { key: "endo_eventos", label: "Eventos" },
      { key: "reconhecimento", label: "Reconhecimento" },
      { key: "endo_comunicacao", label: "Comunicação" },
    ],
  },
  {
    key: "trade",
    label: "19. Trade Marketing",
    itens: [
      { key: "pdv", label: "PDV" },
      { key: "trade_ativacoes", label: "Ativações" },
      { key: "promotores", label: "Promotores" },
      { key: "blitz", label: "Blitz" },
      { key: "degustacoes", label: "Degustações" },
      { key: "sampling", label: "Sampling" },
      { key: "trade_merchandising", label: "Merchandising" },
    ],
  },
  {
    key: "vendas",
    label: "20. Soluções para Vendas",
    itens: [
      { key: "geracao_leads", label: "Geração de Leads" },
      { key: "vendas_crm", label: "CRM" },
      { key: "automacao", label: "Automação" },
      { key: "whatsapp_business", label: "WhatsApp Business" },
      { key: "email_mkt", label: "E-mail Marketing" },
      { key: "funis", label: "Funis" },
      { key: "chatbots", label: "Chatbots" },
    ],
  },
  {
    key: "licitacoes",
    label: "21. Licitações e Projetos",
    itens: [
      { key: "proj_institucionais", label: "Projetos Institucionais" },
      { key: "com_governamental", label: "Comunicação Governamental" },
      { key: "eventos_publicos", label: "Eventos Públicos" },
      { key: "leis_incentivo", label: "Patrocínio via Leis de Incentivo" },
    ],
  },
  {
    key: "solucoes",
    label: "22. Soluções Exclusivas",
    itens: [
      { key: "sol_compra_midia", label: "Compra de mídia em qualquer veículo" },
      { key: "sol_negociacao_descontos", label: "Negociação de descontos" },
      { key: "sol_planejamento_360", label: "Planejamento de campanhas 360º" },
      { key: "sol_representacao", label: "Representação comercial de veículos" },
      { key: "sol_comercializacao", label: "Comercialização de espaços publicitários" },
      { key: "sol_patrocinios", label: "Gestão de patrocínios" },
      { key: "sol_projetos_especiais", label: "Desenvolvimento de projetos especiais" },
      { key: "sol_promocionais", label: "Criação de ações promocionais" },
      { key: "sol_ativacoes", label: "Ativações de marca" },
      { key: "sol_relatorios", label: "Relatórios completos de desempenho" },
      { key: "sol_gestao_completa", label: "Gestão de campanhas ponta a ponta" },
      { key: "sol_consultoria", label: "Consultoria estratégica" },
    ],
  },
];

/** Todas as chaves válidas em ordem de leitura. */
export const CATEGORIAS_KEYS: string[] = CATEGORIAS_SERVICOS.flatMap((g) =>
  g.itens.flatMap((i) => [i.key, ...(i.subitens?.map((s) => s.key) ?? [])]),
);
