/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VeiculosRouteImport } from './routes/veiculos'
import { Route as UsuariosRouteImport } from './routes/usuarios'
import { Route as TarefasRouteImport } from './routes/tarefas'
import { Route as SocialMediaRouteImport } from './routes/social-media'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SiteRouteImport } from './routes/site'
import { Route as RelatoriosRouteImport } from './routes/relatorios'
import { Route as RelatorioSincronizacaoRouteImport } from './routes/relatorio-sincronizacao'
import { Route as PropostasRouteImport } from './routes/propostas'
import { Route as ProjetosEspeciaisRouteImport } from './routes/projetos-especiais'
import { Route as ProdutosRouteImport } from './routes/produtos'
import { Route as PiAnexosRouteImport } from './routes/pi-anexos'
import { Route as PiRouteImport } from './routes/pi'
import { Route as PermutaRouteImport } from './routes/permuta'
import { Route as ParceirosRouteImport } from './routes/parceiros'
import { Route as OwnerRouteImport } from './routes/owner'
import { Route as MonitoramentoRouteImport } from './routes/monitoramento'
import { Route as MinhaContaRouteImport } from './routes/minha-conta'
import { Route as MetasRouteImport } from './routes/metas'
import { Route as MateriaisApoioRouteImport } from './routes/materiais-apoio'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LixeiraRouteImport } from './routes/lixeira'
import { Route as LayoutsRouteImport } from './routes/layouts'
import { Route as LandingPagesRouteImport } from './routes/landing-pages'
import { Route as InfluenciadoresRouteImport } from './routes/influenciadores'
import { Route as HistoricoVeiculacaoRouteImport } from './routes/historico-veiculacao'
import { Route as HistoricoRouteImport } from './routes/historico'
import { Route as FinanceiroRouteImport } from './routes/financeiro'
import { Route as DocumentacaoRouteImport } from './routes/documentacao'
import { Route as CrmRouteImport } from './routes/crm'
import { Route as ConfiguracoesRouteImport } from './routes/configuracoes'
import { Route as ComissoesRouteImport } from './routes/comissoes'
import { Route as ClientesRouteImport } from './routes/clientes'
import { Route as CalendarioRouteImport } from './routes/calendario'
import { Route as BriefingsRouteImport } from './routes/briefings'
import { Route as AgenciasRouteImport } from './routes/agencias'
import { Route as SlugRouteImport } from './routes/$slug'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SiteIndexRouteImport } from './routes/site.index'
import { Route as SiteTermosRouteImport } from './routes/site.termos'
import { Route as SiteRecursosRouteImport } from './routes/site.recursos'
import { Route as SitePrivacidadeRouteImport } from './routes/site.privacidade'
import { Route as SitePrecosRouteImport } from './routes/site.precos'
import { Route as SiteDemoRouteImport } from './routes/site.demo'
import { Route as SiteContatoRouteImport } from './routes/site.contato'
import { Route as PosVendaTokenRouteImport } from './routes/pos-venda.$token'
import { Route as LpSlugRouteImport } from './routes/lp.$slug'
import { Route as LandingPagesIdRouteImport } from './routes/landing-pages.$id'
import { Route as EmailUnsubscribeRouteImport } from './routes/email/unsubscribe'
import { Route as AssinarTokenRouteImport } from './routes/assinar.$token'
import { Route as AprovarDiretoriaTokenRouteImport } from './routes/aprovar-diretoria.$token'
import { Route as LovableEmailSuppressionRouteImport } from './routes/lovable/email/suppression'
import { Route as LovableEmailTransactionalSendRouteImport } from './routes/lovable/email/transactional/send'
import { Route as LovableEmailTransactionalPreviewRouteImport } from './routes/lovable/email/transactional/preview'
import { Route as LovableEmailQueueProcessRouteImport } from './routes/lovable/email/queue/process'
import { Route as ApiPublicPiShareTokenRouteImport } from './routes/api/public/pi-share.$token'
import { Route as ApiPublicHooksSyncCnpjRouteImport } from './routes/api/public/hooks/sync-cnpj'
import { Route as ApiPublicHooksNotificacoesJobRouteImport } from './routes/api/public/hooks/notificacoes-job'

const VeiculosRoute = VeiculosRouteImport.update({
  id: '/veiculos',
  path: '/veiculos',
  getParentRoute: () => rootRouteImport,
} as any)
const UsuariosRoute = UsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => rootRouteImport,
} as any)
const TarefasRoute = TarefasRouteImport.update({
  id: '/tarefas',
  path: '/tarefas',
  getParentRoute: () => rootRouteImport,
} as any)
const SocialMediaRoute = SocialMediaRouteImport.update({
  id: '/social-media',
  path: '/social-media',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SiteRoute = SiteRouteImport.update({
  id: '/site',
  path: '/site',
  getParentRoute: () => rootRouteImport,
} as any)
const RelatoriosRoute = RelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => rootRouteImport,
} as any)
const RelatorioSincronizacaoRoute = RelatorioSincronizacaoRouteImport.update({
  id: '/relatorio-sincronizacao',
  path: '/relatorio-sincronizacao',
  getParentRoute: () => rootRouteImport,
} as any)
const PropostasRoute = PropostasRouteImport.update({
  id: '/propostas',
  path: '/propostas',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjetosEspeciaisRoute = ProjetosEspeciaisRouteImport.update({
  id: '/projetos-especiais',
  path: '/projetos-especiais',
  getParentRoute: () => rootRouteImport,
} as any)
const ProdutosRoute = ProdutosRouteImport.update({
  id: '/produtos',
  path: '/produtos',
  getParentRoute: () => rootRouteImport,
} as any)
const PiAnexosRoute = PiAnexosRouteImport.update({
  id: '/pi-anexos',
  path: '/pi-anexos',
  getParentRoute: () => rootRouteImport,
} as any)
const PiRoute = PiRouteImport.update({
  id: '/pi',
  path: '/pi',
  getParentRoute: () => rootRouteImport,
} as any)
const PermutaRoute = PermutaRouteImport.update({
  id: '/permuta',
  path: '/permuta',
  getParentRoute: () => rootRouteImport,
} as any)
const ParceirosRoute = ParceirosRouteImport.update({
  id: '/parceiros',
  path: '/parceiros',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerRoute = OwnerRouteImport.update({
  id: '/owner',
  path: '/owner',
  getParentRoute: () => rootRouteImport,
} as any)
const MonitoramentoRoute = MonitoramentoRouteImport.update({
  id: '/monitoramento',
  path: '/monitoramento',
  getParentRoute: () => rootRouteImport,
} as any)
const MinhaContaRoute = MinhaContaRouteImport.update({
  id: '/minha-conta',
  path: '/minha-conta',
  getParentRoute: () => rootRouteImport,
} as any)
const MetasRoute = MetasRouteImport.update({
  id: '/metas',
  path: '/metas',
  getParentRoute: () => rootRouteImport,
} as any)
const MateriaisApoioRoute = MateriaisApoioRouteImport.update({
  id: '/materiais-apoio',
  path: '/materiais-apoio',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LixeiraRoute = LixeiraRouteImport.update({
  id: '/lixeira',
  path: '/lixeira',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutsRoute = LayoutsRouteImport.update({
  id: '/layouts',
  path: '/layouts',
  getParentRoute: () => rootRouteImport,
} as any)
const LandingPagesRoute = LandingPagesRouteImport.update({
  id: '/landing-pages',
  path: '/landing-pages',
  getParentRoute: () => rootRouteImport,
} as any)
const InfluenciadoresRoute = InfluenciadoresRouteImport.update({
  id: '/influenciadores',
  path: '/influenciadores',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoricoVeiculacaoRoute = HistoricoVeiculacaoRouteImport.update({
  id: '/historico-veiculacao',
  path: '/historico-veiculacao',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoricoRoute = HistoricoRouteImport.update({
  id: '/historico',
  path: '/historico',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceiroRoute = FinanceiroRouteImport.update({
  id: '/financeiro',
  path: '/financeiro',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentacaoRoute = DocumentacaoRouteImport.update({
  id: '/documentacao',
  path: '/documentacao',
  getParentRoute: () => rootRouteImport,
} as any)
const CrmRoute = CrmRouteImport.update({
  id: '/crm',
  path: '/crm',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracoesRoute = ConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => rootRouteImport,
} as any)
const ComissoesRoute = ComissoesRouteImport.update({
  id: '/comissoes',
  path: '/comissoes',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientesRoute = ClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarioRoute = CalendarioRouteImport.update({
  id: '/calendario',
  path: '/calendario',
  getParentRoute: () => rootRouteImport,
} as any)
const BriefingsRoute = BriefingsRouteImport.update({
  id: '/briefings',
  path: '/briefings',
  getParentRoute: () => rootRouteImport,
} as any)
const AgenciasRoute = AgenciasRouteImport.update({
  id: '/agencias',
  path: '/agencias',
  getParentRoute: () => rootRouteImport,
} as any)
const SlugRoute = SlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SiteIndexRoute = SiteIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SiteRoute,
} as any)
const SiteTermosRoute = SiteTermosRouteImport.update({
  id: '/termos',
  path: '/termos',
  getParentRoute: () => SiteRoute,
} as any)
const SiteRecursosRoute = SiteRecursosRouteImport.update({
  id: '/recursos',
  path: '/recursos',
  getParentRoute: () => SiteRoute,
} as any)
const SitePrivacidadeRoute = SitePrivacidadeRouteImport.update({
  id: '/privacidade',
  path: '/privacidade',
  getParentRoute: () => SiteRoute,
} as any)
const SitePrecosRoute = SitePrecosRouteImport.update({
  id: '/precos',
  path: '/precos',
  getParentRoute: () => SiteRoute,
} as any)
const SiteDemoRoute = SiteDemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => SiteRoute,
} as any)
const SiteContatoRoute = SiteContatoRouteImport.update({
  id: '/contato',
  path: '/contato',
  getParentRoute: () => SiteRoute,
} as any)
const PosVendaTokenRoute = PosVendaTokenRouteImport.update({
  id: '/pos-venda/$token',
  path: '/pos-venda/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const LpSlugRoute = LpSlugRouteImport.update({
  id: '/lp/$slug',
  path: '/lp/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const LandingPagesIdRoute = LandingPagesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => LandingPagesRoute,
} as any)
const EmailUnsubscribeRoute = EmailUnsubscribeRouteImport.update({
  id: '/email/unsubscribe',
  path: '/email/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const AssinarTokenRoute = AssinarTokenRouteImport.update({
  id: '/assinar/$token',
  path: '/assinar/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AprovarDiretoriaTokenRoute = AprovarDiretoriaTokenRouteImport.update({
  id: '/aprovar-diretoria/$token',
  path: '/aprovar-diretoria/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailSuppressionRoute = LovableEmailSuppressionRouteImport.update({
  id: '/lovable/email/suppression',
  path: '/lovable/email/suppression',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailTransactionalSendRoute =
  LovableEmailTransactionalSendRouteImport.update({
    id: '/lovable/email/transactional/send',
    path: '/lovable/email/transactional/send',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailTransactionalPreviewRoute =
  LovableEmailTransactionalPreviewRouteImport.update({
    id: '/lovable/email/transactional/preview',
    path: '/lovable/email/transactional/preview',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailQueueProcessRoute =
  LovableEmailQueueProcessRouteImport.update({
    id: '/lovable/email/queue/process',
    path: '/lovable/email/queue/process',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicPiShareTokenRoute = ApiPublicPiShareTokenRouteImport.update({
  id: '/api/public/pi-share/$token',
  path: '/api/public/pi-share/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksSyncCnpjRoute = ApiPublicHooksSyncCnpjRouteImport.update({
  id: '/api/public/hooks/sync-cnpj',
  path: '/api/public/hooks/sync-cnpj',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksNotificacoesJobRoute =
  ApiPublicHooksNotificacoesJobRouteImport.update({
    id: '/api/public/hooks/notificacoes-job',
    path: '/api/public/hooks/notificacoes-job',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$slug': typeof SlugRoute
  '/agencias': typeof AgenciasRoute
  '/briefings': typeof BriefingsRoute
  '/calendario': typeof CalendarioRoute
  '/clientes': typeof ClientesRoute
  '/comissoes': typeof ComissoesRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/crm': typeof CrmRoute
  '/documentacao': typeof DocumentacaoRoute
  '/financeiro': typeof FinanceiroRoute
  '/historico': typeof HistoricoRoute
  '/historico-veiculacao': typeof HistoricoVeiculacaoRoute
  '/influenciadores': typeof InfluenciadoresRoute
  '/landing-pages': typeof LandingPagesRouteWithChildren
  '/layouts': typeof LayoutsRoute
  '/lixeira': typeof LixeiraRoute
  '/login': typeof LoginRoute
  '/materiais-apoio': typeof MateriaisApoioRoute
  '/metas': typeof MetasRoute
  '/minha-conta': typeof MinhaContaRoute
  '/monitoramento': typeof MonitoramentoRoute
  '/owner': typeof OwnerRoute
  '/parceiros': typeof ParceirosRoute
  '/permuta': typeof PermutaRoute
  '/pi': typeof PiRoute
  '/pi-anexos': typeof PiAnexosRoute
  '/produtos': typeof ProdutosRoute
  '/projetos-especiais': typeof ProjetosEspeciaisRoute
  '/propostas': typeof PropostasRoute
  '/relatorio-sincronizacao': typeof RelatorioSincronizacaoRoute
  '/relatorios': typeof RelatoriosRoute
  '/site': typeof SiteRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/social-media': typeof SocialMediaRoute
  '/tarefas': typeof TarefasRoute
  '/usuarios': typeof UsuariosRoute
  '/veiculos': typeof VeiculosRoute
  '/aprovar-diretoria/$token': typeof AprovarDiretoriaTokenRoute
  '/assinar/$token': typeof AssinarTokenRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/landing-pages/$id': typeof LandingPagesIdRoute
  '/lp/$slug': typeof LpSlugRoute
  '/pos-venda/$token': typeof PosVendaTokenRoute
  '/site/contato': typeof SiteContatoRoute
  '/site/demo': typeof SiteDemoRoute
  '/site/precos': typeof SitePrecosRoute
  '/site/privacidade': typeof SitePrivacidadeRoute
  '/site/recursos': typeof SiteRecursosRoute
  '/site/termos': typeof SiteTermosRoute
  '/site/': typeof SiteIndexRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/api/public/hooks/notificacoes-job': typeof ApiPublicHooksNotificacoesJobRoute
  '/api/public/hooks/sync-cnpj': typeof ApiPublicHooksSyncCnpjRoute
  '/api/public/pi-share/$token': typeof ApiPublicPiShareTokenRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$slug': typeof SlugRoute
  '/agencias': typeof AgenciasRoute
  '/briefings': typeof BriefingsRoute
  '/calendario': typeof CalendarioRoute
  '/clientes': typeof ClientesRoute
  '/comissoes': typeof ComissoesRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/crm': typeof CrmRoute
  '/documentacao': typeof DocumentacaoRoute
  '/financeiro': typeof FinanceiroRoute
  '/historico': typeof HistoricoRoute
  '/historico-veiculacao': typeof HistoricoVeiculacaoRoute
  '/influenciadores': typeof InfluenciadoresRoute
  '/landing-pages': typeof LandingPagesRouteWithChildren
  '/layouts': typeof LayoutsRoute
  '/lixeira': typeof LixeiraRoute
  '/login': typeof LoginRoute
  '/materiais-apoio': typeof MateriaisApoioRoute
  '/metas': typeof MetasRoute
  '/minha-conta': typeof MinhaContaRoute
  '/monitoramento': typeof MonitoramentoRoute
  '/owner': typeof OwnerRoute
  '/parceiros': typeof ParceirosRoute
  '/permuta': typeof PermutaRoute
  '/pi': typeof PiRoute
  '/pi-anexos': typeof PiAnexosRoute
  '/produtos': typeof ProdutosRoute
  '/projetos-especiais': typeof ProjetosEspeciaisRoute
  '/propostas': typeof PropostasRoute
  '/relatorio-sincronizacao': typeof RelatorioSincronizacaoRoute
  '/relatorios': typeof RelatoriosRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/social-media': typeof SocialMediaRoute
  '/tarefas': typeof TarefasRoute
  '/usuarios': typeof UsuariosRoute
  '/veiculos': typeof VeiculosRoute
  '/aprovar-diretoria/$token': typeof AprovarDiretoriaTokenRoute
  '/assinar/$token': typeof AssinarTokenRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/landing-pages/$id': typeof LandingPagesIdRoute
  '/lp/$slug': typeof LpSlugRoute
  '/pos-venda/$token': typeof PosVendaTokenRoute
  '/site/contato': typeof SiteContatoRoute
  '/site/demo': typeof SiteDemoRoute
  '/site/precos': typeof SitePrecosRoute
  '/site/privacidade': typeof SitePrivacidadeRoute
  '/site/recursos': typeof SiteRecursosRoute
  '/site/termos': typeof SiteTermosRoute
  '/site': typeof SiteIndexRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/api/public/hooks/notificacoes-job': typeof ApiPublicHooksNotificacoesJobRoute
  '/api/public/hooks/sync-cnpj': typeof ApiPublicHooksSyncCnpjRoute
  '/api/public/pi-share/$token': typeof ApiPublicPiShareTokenRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$slug': typeof SlugRoute
  '/agencias': typeof AgenciasRoute
  '/briefings': typeof BriefingsRoute
  '/calendario': typeof CalendarioRoute
  '/clientes': typeof ClientesRoute
  '/comissoes': typeof ComissoesRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/crm': typeof CrmRoute
  '/documentacao': typeof DocumentacaoRoute
  '/financeiro': typeof FinanceiroRoute
  '/historico': typeof HistoricoRoute
  '/historico-veiculacao': typeof HistoricoVeiculacaoRoute
  '/influenciadores': typeof InfluenciadoresRoute
  '/landing-pages': typeof LandingPagesRouteWithChildren
  '/layouts': typeof LayoutsRoute
  '/lixeira': typeof LixeiraRoute
  '/login': typeof LoginRoute
  '/materiais-apoio': typeof MateriaisApoioRoute
  '/metas': typeof MetasRoute
  '/minha-conta': typeof MinhaContaRoute
  '/monitoramento': typeof MonitoramentoRoute
  '/owner': typeof OwnerRoute
  '/parceiros': typeof ParceirosRoute
  '/permuta': typeof PermutaRoute
  '/pi': typeof PiRoute
  '/pi-anexos': typeof PiAnexosRoute
  '/produtos': typeof ProdutosRoute
  '/projetos-especiais': typeof ProjetosEspeciaisRoute
  '/propostas': typeof PropostasRoute
  '/relatorio-sincronizacao': typeof RelatorioSincronizacaoRoute
  '/relatorios': typeof RelatoriosRoute
  '/site': typeof SiteRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/social-media': typeof SocialMediaRoute
  '/tarefas': typeof TarefasRoute
  '/usuarios': typeof UsuariosRoute
  '/veiculos': typeof VeiculosRoute
  '/aprovar-diretoria/$token': typeof AprovarDiretoriaTokenRoute
  '/assinar/$token': typeof AssinarTokenRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/landing-pages/$id': typeof LandingPagesIdRoute
  '/lp/$slug': typeof LpSlugRoute
  '/pos-venda/$token': typeof PosVendaTokenRoute
  '/site/contato': typeof SiteContatoRoute
  '/site/demo': typeof SiteDemoRoute
  '/site/precos': typeof SitePrecosRoute
  '/site/privacidade': typeof SitePrivacidadeRoute
  '/site/recursos': typeof SiteRecursosRoute
  '/site/termos': typeof SiteTermosRoute
  '/site/': typeof SiteIndexRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/api/public/hooks/notificacoes-job': typeof ApiPublicHooksNotificacoesJobRoute
  '/api/public/hooks/sync-cnpj': typeof ApiPublicHooksSyncCnpjRoute
  '/api/public/pi-share/$token': typeof ApiPublicPiShareTokenRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$slug'
    | '/agencias'
    | '/briefings'
    | '/calendario'
    | '/clientes'
    | '/comissoes'
    | '/configuracoes'
    | '/crm'
    | '/documentacao'
    | '/financeiro'
    | '/historico'
    | '/historico-veiculacao'
    | '/influenciadores'
    | '/landing-pages'
    | '/layouts'
    | '/lixeira'
    | '/login'
    | '/materiais-apoio'
    | '/metas'
    | '/minha-conta'
    | '/monitoramento'
    | '/owner'
    | '/parceiros'
    | '/permuta'
    | '/pi'
    | '/pi-anexos'
    | '/produtos'
    | '/projetos-especiais'
    | '/propostas'
    | '/relatorio-sincronizacao'
    | '/relatorios'
    | '/site'
    | '/sitemap.xml'
    | '/social-media'
    | '/tarefas'
    | '/usuarios'
    | '/veiculos'
    | '/aprovar-diretoria/$token'
    | '/assinar/$token'
    | '/email/unsubscribe'
    | '/landing-pages/$id'
    | '/lp/$slug'
    | '/pos-venda/$token'
    | '/site/contato'
    | '/site/demo'
    | '/site/precos'
    | '/site/privacidade'
    | '/site/recursos'
    | '/site/termos'
    | '/site/'
    | '/lovable/email/suppression'
    | '/api/public/hooks/notificacoes-job'
    | '/api/public/hooks/sync-cnpj'
    | '/api/public/pi-share/$token'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$slug'
    | '/agencias'
    | '/briefings'
    | '/calendario'
    | '/clientes'
    | '/comissoes'
    | '/configuracoes'
    | '/crm'
    | '/documentacao'
    | '/financeiro'
    | '/historico'
    | '/historico-veiculacao'
    | '/influenciadores'
    | '/landing-pages'
    | '/layouts'
    | '/lixeira'
    | '/login'
    | '/materiais-apoio'
    | '/metas'
    | '/minha-conta'
    | '/monitoramento'
    | '/owner'
    | '/parceiros'
    | '/permuta'
    | '/pi'
    | '/pi-anexos'
    | '/produtos'
    | '/projetos-especiais'
    | '/propostas'
    | '/relatorio-sincronizacao'
    | '/relatorios'
    | '/sitemap.xml'
    | '/social-media'
    | '/tarefas'
    | '/usuarios'
    | '/veiculos'
    | '/aprovar-diretoria/$token'
    | '/assinar/$token'
    | '/email/unsubscribe'
    | '/landing-pages/$id'
    | '/lp/$slug'
    | '/pos-venda/$token'
    | '/site/contato'
    | '/site/demo'
    | '/site/precos'
    | '/site/privacidade'
    | '/site/recursos'
    | '/site/termos'
    | '/site'
    | '/lovable/email/suppression'
    | '/api/public/hooks/notificacoes-job'
    | '/api/public/hooks/sync-cnpj'
    | '/api/public/pi-share/$token'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  id:
    | '__root__'
    | '/'
    | '/$slug'
    | '/agencias'
    | '/briefings'
    | '/calendario'
    | '/clientes'
    | '/comissoes'
    | '/configuracoes'
    | '/crm'
    | '/documentacao'
    | '/financeiro'
    | '/historico'
    | '/historico-veiculacao'
    | '/influenciadores'
    | '/landing-pages'
    | '/layouts'
    | '/lixeira'
    | '/login'
    | '/materiais-apoio'
    | '/metas'
    | '/minha-conta'
    | '/monitoramento'
    | '/owner'
    | '/parceiros'
    | '/permuta'
    | '/pi'
    | '/pi-anexos'
    | '/produtos'
    | '/projetos-especiais'
    | '/propostas'
    | '/relatorio-sincronizacao'
    | '/relatorios'
    | '/site'
    | '/sitemap.xml'
    | '/social-media'
    | '/tarefas'
    | '/usuarios'
    | '/veiculos'
    | '/aprovar-diretoria/$token'
    | '/assinar/$token'
    | '/email/unsubscribe'
    | '/landing-pages/$id'
    | '/lp/$slug'
    | '/pos-venda/$token'
    | '/site/contato'
    | '/site/demo'
    | '/site/precos'
    | '/site/privacidade'
    | '/site/recursos'
    | '/site/termos'
    | '/site/'
    | '/lovable/email/suppression'
    | '/api/public/hooks/notificacoes-job'
    | '/api/public/hooks/sync-cnpj'
    | '/api/public/pi-share/$token'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SlugRoute: typeof SlugRoute
  AgenciasRoute: typeof AgenciasRoute
  BriefingsRoute: typeof BriefingsRoute
  CalendarioRoute: typeof CalendarioRoute
  ClientesRoute: typeof ClientesRoute
  ComissoesRoute: typeof ComissoesRoute
  ConfiguracoesRoute: typeof ConfiguracoesRoute
  CrmRoute: typeof CrmRoute
  DocumentacaoRoute: typeof DocumentacaoRoute
  FinanceiroRoute: typeof FinanceiroRoute
  HistoricoRoute: typeof HistoricoRoute
  HistoricoVeiculacaoRoute: typeof HistoricoVeiculacaoRoute
  InfluenciadoresRoute: typeof InfluenciadoresRoute
  LandingPagesRoute: typeof LandingPagesRouteWithChildren
  LayoutsRoute: typeof LayoutsRoute
  LixeiraRoute: typeof LixeiraRoute
  LoginRoute: typeof LoginRoute
  MateriaisApoioRoute: typeof MateriaisApoioRoute
  MetasRoute: typeof MetasRoute
  MinhaContaRoute: typeof MinhaContaRoute
  MonitoramentoRoute: typeof MonitoramentoRoute
  OwnerRoute: typeof OwnerRoute
  ParceirosRoute: typeof ParceirosRoute
  PermutaRoute: typeof PermutaRoute
  PiRoute: typeof PiRoute
  PiAnexosRoute: typeof PiAnexosRoute
  ProdutosRoute: typeof ProdutosRoute
  ProjetosEspeciaisRoute: typeof ProjetosEspeciaisRoute
  PropostasRoute: typeof PropostasRoute
  RelatorioSincronizacaoRoute: typeof RelatorioSincronizacaoRoute
  RelatoriosRoute: typeof RelatoriosRoute
  SiteRoute: typeof SiteRouteWithChildren
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SocialMediaRoute: typeof SocialMediaRoute
  TarefasRoute: typeof TarefasRoute
  UsuariosRoute: typeof UsuariosRoute
  VeiculosRoute: typeof VeiculosRoute
  AprovarDiretoriaTokenRoute: typeof AprovarDiretoriaTokenRoute
  AssinarTokenRoute: typeof AssinarTokenRoute
  EmailUnsubscribeRoute: typeof EmailUnsubscribeRoute
  LpSlugRoute: typeof LpSlugRoute
  PosVendaTokenRoute: typeof PosVendaTokenRoute
  LovableEmailSuppressionRoute: typeof LovableEmailSuppressionRoute
  ApiPublicHooksNotificacoesJobRoute: typeof ApiPublicHooksNotificacoesJobRoute
  ApiPublicHooksSyncCnpjRoute: typeof ApiPublicHooksSyncCnpjRoute
  ApiPublicPiShareTokenRoute: typeof ApiPublicPiShareTokenRoute
  LovableEmailQueueProcessRoute: typeof LovableEmailQueueProcessRoute
  LovableEmailTransactionalPreviewRoute: typeof LovableEmailTransactionalPreviewRoute
  LovableEmailTransactionalSendRoute: typeof LovableEmailTransactionalSendRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/veiculos': {
      id: '/veiculos'
      path: '/veiculos'
      fullPath: '/veiculos'
      preLoaderRoute: typeof VeiculosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/usuarios': {
      id: '/usuarios'
      path: '/usuarios'
      fullPath: '/usuarios'
      preLoaderRoute: typeof UsuariosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tarefas': {
      id: '/tarefas'
      path: '/tarefas'
      fullPath: '/tarefas'
      preLoaderRoute: typeof TarefasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/social-media': {
      id: '/social-media'
      path: '/social-media'
      fullPath: '/social-media'
      preLoaderRoute: typeof SocialMediaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/site': {
      id: '/site'
      path: '/site'
      fullPath: '/site'
      preLoaderRoute: typeof SiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/relatorios': {
      id: '/relatorios'
      path: '/relatorios'
      fullPath: '/relatorios'
      preLoaderRoute: typeof RelatoriosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/relatorio-sincronizacao': {
      id: '/relatorio-sincronizacao'
      path: '/relatorio-sincronizacao'
      fullPath: '/relatorio-sincronizacao'
      preLoaderRoute: typeof RelatorioSincronizacaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/propostas': {
      id: '/propostas'
      path: '/propostas'
      fullPath: '/propostas'
      preLoaderRoute: typeof PropostasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projetos-especiais': {
      id: '/projetos-especiais'
      path: '/projetos-especiais'
      fullPath: '/projetos-especiais'
      preLoaderRoute: typeof ProjetosEspeciaisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produtos': {
      id: '/produtos'
      path: '/produtos'
      fullPath: '/produtos'
      preLoaderRoute: typeof ProdutosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pi-anexos': {
      id: '/pi-anexos'
      path: '/pi-anexos'
      fullPath: '/pi-anexos'
      preLoaderRoute: typeof PiAnexosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pi': {
      id: '/pi'
      path: '/pi'
      fullPath: '/pi'
      preLoaderRoute: typeof PiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/permuta': {
      id: '/permuta'
      path: '/permuta'
      fullPath: '/permuta'
      preLoaderRoute: typeof PermutaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parceiros': {
      id: '/parceiros'
      path: '/parceiros'
      fullPath: '/parceiros'
      preLoaderRoute: typeof ParceirosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/owner': {
      id: '/owner'
      path: '/owner'
      fullPath: '/owner'
      preLoaderRoute: typeof OwnerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/monitoramento': {
      id: '/monitoramento'
      path: '/monitoramento'
      fullPath: '/monitoramento'
      preLoaderRoute: typeof MonitoramentoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/minha-conta': {
      id: '/minha-conta'
      path: '/minha-conta'
      fullPath: '/minha-conta'
      preLoaderRoute: typeof MinhaContaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/metas': {
      id: '/metas'
      path: '/metas'
      fullPath: '/metas'
      preLoaderRoute: typeof MetasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/materiais-apoio': {
      id: '/materiais-apoio'
      path: '/materiais-apoio'
      fullPath: '/materiais-apoio'
      preLoaderRoute: typeof MateriaisApoioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lixeira': {
      id: '/lixeira'
      path: '/lixeira'
      fullPath: '/lixeira'
      preLoaderRoute: typeof LixeiraRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/layouts': {
      id: '/layouts'
      path: '/layouts'
      fullPath: '/layouts'
      preLoaderRoute: typeof LayoutsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/landing-pages': {
      id: '/landing-pages'
      path: '/landing-pages'
      fullPath: '/landing-pages'
      preLoaderRoute: typeof LandingPagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/influenciadores': {
      id: '/influenciadores'
      path: '/influenciadores'
      fullPath: '/influenciadores'
      preLoaderRoute: typeof InfluenciadoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/historico-veiculacao': {
      id: '/historico-veiculacao'
      path: '/historico-veiculacao'
      fullPath: '/historico-veiculacao'
      preLoaderRoute: typeof HistoricoVeiculacaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/historico': {
      id: '/historico'
      path: '/historico'
      fullPath: '/historico'
      preLoaderRoute: typeof HistoricoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/financeiro': {
      id: '/financeiro'
      path: '/financeiro'
      fullPath: '/financeiro'
      preLoaderRoute: typeof FinanceiroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documentacao': {
      id: '/documentacao'
      path: '/documentacao'
      fullPath: '/documentacao'
      preLoaderRoute: typeof DocumentacaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crm': {
      id: '/crm'
      path: '/crm'
      fullPath: '/crm'
      preLoaderRoute: typeof CrmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracoes': {
      id: '/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof ConfiguracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comissoes': {
      id: '/comissoes'
      path: '/comissoes'
      fullPath: '/comissoes'
      preLoaderRoute: typeof ComissoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clientes': {
      id: '/clientes'
      path: '/clientes'
      fullPath: '/clientes'
      preLoaderRoute: typeof ClientesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendario': {
      id: '/calendario'
      path: '/calendario'
      fullPath: '/calendario'
      preLoaderRoute: typeof CalendarioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/briefings': {
      id: '/briefings'
      path: '/briefings'
      fullPath: '/briefings'
      preLoaderRoute: typeof BriefingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agencias': {
      id: '/agencias'
      path: '/agencias'
      fullPath: '/agencias'
      preLoaderRoute: typeof AgenciasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$slug': {
      id: '/$slug'
      path: '/$slug'
      fullPath: '/$slug'
      preLoaderRoute: typeof SlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/site/': {
      id: '/site/'
      path: '/'
      fullPath: '/site/'
      preLoaderRoute: typeof SiteIndexRouteImport
      parentRoute: typeof SiteRoute
    }
    '/site/termos': {
      id: '/site/termos'
      path: '/termos'
      fullPath: '/site/termos'
      preLoaderRoute: typeof SiteTermosRouteImport
      parentRoute: typeof SiteRoute
    }
    '/site/recursos': {
      id: '/site/recursos'
      path: '/recursos'
      fullPath: '/site/recursos'
      preLoaderRoute: typeof SiteRecursosRouteImport
      parentRoute: typeof SiteRoute
    }
    '/site/privacidade': {
      id: '/site/privacidade'
      path: '/privacidade'
      fullPath: '/site/privacidade'
      preLoaderRoute: typeof SitePrivacidadeRouteImport
      parentRoute: typeof SiteRoute
    }
    '/site/precos': {
      id: '/site/precos'
      path: '/precos'
      fullPath: '/site/precos'
      preLoaderRoute: typeof SitePrecosRouteImport
      parentRoute: typeof SiteRoute
    }
    '/site/demo': {
      id: '/site/demo'
      path: '/demo'
      fullPath: '/site/demo'
      preLoaderRoute: typeof SiteDemoRouteImport
      parentRoute: typeof SiteRoute
    }
    '/site/contato': {
      id: '/site/contato'
      path: '/contato'
      fullPath: '/site/contato'
      preLoaderRoute: typeof SiteContatoRouteImport
      parentRoute: typeof SiteRoute
    }
    '/pos-venda/$token': {
      id: '/pos-venda/$token'
      path: '/pos-venda/$token'
      fullPath: '/pos-venda/$token'
      preLoaderRoute: typeof PosVendaTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lp/$slug': {
      id: '/lp/$slug'
      path: '/lp/$slug'
      fullPath: '/lp/$slug'
      preLoaderRoute: typeof LpSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/landing-pages/$id': {
      id: '/landing-pages/$id'
      path: '/$id'
      fullPath: '/landing-pages/$id'
      preLoaderRoute: typeof LandingPagesIdRouteImport
      parentRoute: typeof LandingPagesRoute
    }
    '/email/unsubscribe': {
      id: '/email/unsubscribe'
      path: '/email/unsubscribe'
      fullPath: '/email/unsubscribe'
      preLoaderRoute: typeof EmailUnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assinar/$token': {
      id: '/assinar/$token'
      path: '/assinar/$token'
      fullPath: '/assinar/$token'
      preLoaderRoute: typeof AssinarTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aprovar-diretoria/$token': {
      id: '/aprovar-diretoria/$token'
      path: '/aprovar-diretoria/$token'
      fullPath: '/aprovar-diretoria/$token'
      preLoaderRoute: typeof AprovarDiretoriaTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/suppression': {
      id: '/lovable/email/suppression'
      path: '/lovable/email/suppression'
      fullPath: '/lovable/email/suppression'
      preLoaderRoute: typeof LovableEmailSuppressionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/send': {
      id: '/lovable/email/transactional/send'
      path: '/lovable/email/transactional/send'
      fullPath: '/lovable/email/transactional/send'
      preLoaderRoute: typeof LovableEmailTransactionalSendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/preview': {
      id: '/lovable/email/transactional/preview'
      path: '/lovable/email/transactional/preview'
      fullPath: '/lovable/email/transactional/preview'
      preLoaderRoute: typeof LovableEmailTransactionalPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/queue/process': {
      id: '/lovable/email/queue/process'
      path: '/lovable/email/queue/process'
      fullPath: '/lovable/email/queue/process'
      preLoaderRoute: typeof LovableEmailQueueProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/pi-share/$token': {
      id: '/api/public/pi-share/$token'
      path: '/api/public/pi-share/$token'
      fullPath: '/api/public/pi-share/$token'
      preLoaderRoute: typeof ApiPublicPiShareTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/sync-cnpj': {
      id: '/api/public/hooks/sync-cnpj'
      path: '/api/public/hooks/sync-cnpj'
      fullPath: '/api/public/hooks/sync-cnpj'
      preLoaderRoute: typeof ApiPublicHooksSyncCnpjRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/notificacoes-job': {
      id: '/api/public/hooks/notificacoes-job'
      path: '/api/public/hooks/notificacoes-job'
      fullPath: '/api/public/hooks/notificacoes-job'
      preLoaderRoute: typeof ApiPublicHooksNotificacoesJobRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface LandingPagesRouteChildren {
  LandingPagesIdRoute: typeof LandingPagesIdRoute
}

const LandingPagesRouteChildren: LandingPagesRouteChildren = {
  LandingPagesIdRoute: LandingPagesIdRoute,
}

const LandingPagesRouteWithChildren = LandingPagesRoute._addFileChildren(
  LandingPagesRouteChildren,
)

interface SiteRouteChildren {
  SiteContatoRoute: typeof SiteContatoRoute
  SiteDemoRoute: typeof SiteDemoRoute
  SitePrecosRoute: typeof SitePrecosRoute
  SitePrivacidadeRoute: typeof SitePrivacidadeRoute
  SiteRecursosRoute: typeof SiteRecursosRoute
  SiteTermosRoute: typeof SiteTermosRoute
  SiteIndexRoute: typeof SiteIndexRoute
}

const SiteRouteChildren: SiteRouteChildren = {
  SiteContatoRoute: SiteContatoRoute,
  SiteDemoRoute: SiteDemoRoute,
  SitePrecosRoute: SitePrecosRoute,
  SitePrivacidadeRoute: SitePrivacidadeRoute,
  SiteRecursosRoute: SiteRecursosRoute,
  SiteTermosRoute: SiteTermosRoute,
  SiteIndexRoute: SiteIndexRoute,
}

const SiteRouteWithChildren = SiteRoute._addFileChildren(SiteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SlugRoute: SlugRoute,
  AgenciasRoute: AgenciasRoute,
  BriefingsRoute: BriefingsRoute,
  CalendarioRoute: CalendarioRoute,
  ClientesRoute: ClientesRoute,
  ComissoesRoute: ComissoesRoute,
  ConfiguracoesRoute: ConfiguracoesRoute,
  CrmRoute: CrmRoute,
  DocumentacaoRoute: DocumentacaoRoute,
  FinanceiroRoute: FinanceiroRoute,
  HistoricoRoute: HistoricoRoute,
  HistoricoVeiculacaoRoute: HistoricoVeiculacaoRoute,
  InfluenciadoresRoute: InfluenciadoresRoute,
  LandingPagesRoute: LandingPagesRouteWithChildren,
  LayoutsRoute: LayoutsRoute,
  LixeiraRoute: LixeiraRoute,
  LoginRoute: LoginRoute,
  MateriaisApoioRoute: MateriaisApoioRoute,
  MetasRoute: MetasRoute,
  MinhaContaRoute: MinhaContaRoute,
  MonitoramentoRoute: MonitoramentoRoute,
  OwnerRoute: OwnerRoute,
  ParceirosRoute: ParceirosRoute,
  PermutaRoute: PermutaRoute,
  PiRoute: PiRoute,
  PiAnexosRoute: PiAnexosRoute,
  ProdutosRoute: ProdutosRoute,
  ProjetosEspeciaisRoute: ProjetosEspeciaisRoute,
  PropostasRoute: PropostasRoute,
  RelatorioSincronizacaoRoute: RelatorioSincronizacaoRoute,
  RelatoriosRoute: RelatoriosRoute,
  SiteRoute: SiteRouteWithChildren,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SocialMediaRoute: SocialMediaRoute,
  TarefasRoute: TarefasRoute,
  UsuariosRoute: UsuariosRoute,
  VeiculosRoute: VeiculosRoute,
  AprovarDiretoriaTokenRoute: AprovarDiretoriaTokenRoute,
  AssinarTokenRoute: AssinarTokenRoute,
  EmailUnsubscribeRoute: EmailUnsubscribeRoute,
  LpSlugRoute: LpSlugRoute,
  PosVendaTokenRoute: PosVendaTokenRoute,
  LovableEmailSuppressionRoute: LovableEmailSuppressionRoute,
  ApiPublicHooksNotificacoesJobRoute: ApiPublicHooksNotificacoesJobRoute,
  ApiPublicHooksSyncCnpjRoute: ApiPublicHooksSyncCnpjRoute,
  ApiPublicPiShareTokenRoute: ApiPublicPiShareTokenRoute,
  LovableEmailQueueProcessRoute: LovableEmailQueueProcessRoute,
  LovableEmailTransactionalPreviewRoute: LovableEmailTransactionalPreviewRoute,
  LovableEmailTransactionalSendRoute: LovableEmailTransactionalSendRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
